services:
  app:
    image: devcontainer-compose:app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HELLO_WORLD=${HELLO_WORLD}

  other_app:
    image: devcontainer-compose:app
    command: python -m app ${HELLO_WORLD}
